version: 0.2

phases:
  install:
    commands:
      - pip install pytest
  build:
    commands:
      - pytest --junitxml=results.xml

reports:
  pytest_reports:
    files:
      - results.xml
    file-format: JUNITXML
